CREATE TABLE wfd_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE saved_recipes (
    PRIMARY KEY("userId", "recipeId"),
    "userId" INTEGER REFERENCES wfd_users(id),
    "recipeId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "sourceUrl" VARCHAR(2048),
    "image" VARCHAR(2048),
    "summary" TEXT NOT NULL
);
